# site settings
title: Billy Blog
subtitle: Billy Byiringiro
email: billybyiringiro@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/billybyiringiro" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Billy
street_address: St Johns Hills 
city: Edinburgh
state: Scotland
zip_code: 55555
country: United Kingdom
phone: 7413710124

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/billyjason
googleplus_url: https://plus.google.com/u/0/103895179042714665770
linkedin_url: https://www.linkedin.com/in/billy-byiringiro/
twitter_url: https://github.com/billyjason

# build settings
markdown: kramdown

sass:
  style: compressed
